# Generated by Django 4.2.6 on 2023-10-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
            ],
        ),
    ]
